### ISSUE TITLE
dnsDomainIs() function mishandles dots as wildcards

### ISSUE THREAD

**Issue by deathbywedgie** [jhthorsen/app-proxyforurl#1]
I don't know if the running sample of proxyforurl at http://home.thorsen.pm/proxyforurl is running the newest code or not, but I seem to have discovered a bug, and I thought you might want to know about it. I discovered today that for the dnsDomainIs function it doesn't process dots (".") in hostnames as actual dots, but rather it processes them as wildcards. For example:

> dnsDomainIs(host, ".cisco.com")

This matches correctly on any subdomain of cisco.com (such as "www.cisco.com"). However, proxyforurl (or at least the version currently in use for the "online proxy PAC file tester" site mentioned above) also matches www.static-cisco.com against it (which is also called by the browser when a user visits www.cisco.com). In other words, the "." in the comparison seems to be treated as a wildcard, such as it is used in regex, thus it matches against "-" when it should not.

I don't know if the same issue applies to any other function besides dnsDomainIs, but I wanted to pass it along.

Thanks for all the effort that you have put into this, by the way!

Warm regards,

/r/Chad
(deathbywedgie)

**Comment by jhthorsen** [comment]
Thanks for reporting in! 👍 

Guess I have to change https://github.com/jhthorsen/app-proxyforurl/blob/master/script/proxyforurl#L147 to:

```
return host.match(new RegExp(domain.replace(/\./, '\\.'), 'i'));
```

Will try to fix it this weekend.

**Comment by jhthorsen** [comment]
I've made a new release and updated http://home.thorsen.pm/proxyforurl

Enjoy!

**Comment by deathbywedgie** [comment]
Just tested... works like a champ! Thanks!
