### ISSUE TITLE
dnsDomainIs misshandling leading characters

### ISSUE THREAD

**Issue by Bender-** [jhthorsen/app-proxyforurl#2]
Hello Jan,

first i´d like to thank you for your tester and also for the informations provided on your website.

I came about an issue. Using this rule as a test:

```
function FindProxyForURL(url, host) {
// If the hostname matches, send direct.
    if (dnsDomainIs(host, "test.com")) return "DIRECT";
return "proxy"}
```

Now:
- if i enter **test.com** i get **direct** as expected :white_check_mark:
- if i enter **test2.com** i get **proxy** as expected :white_check_mark:
- if i enter **1test.com** i get **direct** but i would expect proxy  :x:  

If i  insert any leading chars to the domain i still get direct although the hostname doesn´t match anymore.
Which in my understanding shouldn´t be the case. Since i just started looking into that pac file thing i might be wrong but i guess its a bug. Maybe its a result of the last fixed "dot" issue?

Best regards,
Bender

**Comment by jhthorsen** [comment]
Thank you! The code was completely wrong, since the function should not use a regex matcher at all.

I googled around and ended up copying the code from https://bugs.chromium.org/p/chromium/issues/detail?id=299649
