### ISSUE TITLE
t/gethostbyname.t fails on some systems

### ISSUE THREAD

**Issue by eserte** [jhthorsen/app-proxyforurl#5]
On most of my smoker systems the test suite fails like this:
```
#   Failed test '400 Bad Request'
#   at t/gethostbyname.t line 12.
#          got: '200'
#     expected: '400'
# Looks like you failed 1 test of 9.
t/gethostbyname.t .. 
Dubious, test returned 1 (wstat 256, 0x100)
Failed 1/9 subtests 
```
This happens also on other smoker systems, e.g. http://www.cpantesters.org/cpan/report/3cc706bc-0c4e-11ec-bc66-57723b537541

**Comment by jhthorsen** [comment]
Thanks for reporting in! I hope I managed to fix the issue in 0.10.
