### ISSUE TITLE
t/api.t may fail in the presence of wildcard DNS records

### ISSUE THREAD

**Issue by eserte** [jhthorsen/app-proxyforurl#6]
The test with invalid hostnames in t/api.t fails on some of my smoker systems, probably due to presence of wildcard DNS records. Details about the problem may be found here: https://github.com/tokuhirom/Furl/issues/128

The problem can be reproduced on Linux systems by setting LOCALDOMAIN to a domain which has wildcard DNS records, e.g. bing.com:

```
$ LOCALDOMAIN=bing.com perl5.36.0 -Mblib t/api.t
...
    ok 7 - POST /v1/gethostbyname
    not ok 8 - 400 Bad Request
    #   Failed test '400 Bad Request'
    #   at t/api.t line 15.
    #          got: '200'
    #     expected: '400'
    not ok 9 - exact match for content
    #   Failed test 'exact match for content'
    #   at t/api.t line 15.
    #          got: '13.107.22.200'
    #     expected: 'No IP found for asdasdasdasdsdasd.com'
    ok 10 - POST /v1/gethostbyname
...
```

A possible fix is to add a trailing dot to all invalid hostnames to treat it as a "final" hostname.

**Comment by jhthorsen** [comment]
I decided to just skip the test, since it's not really important unless you are making changes while developing.
